const GOOGLE_FONTS_CDN = 'https://fonts.gstatic.com/s';
const FONTSHARE_CDN = 'https://fontshare.b-cdn.net/wf';

export default {
  Raleway: `${GOOGLE_FONTS_CDN}/raleway/v14/1Ptrg8zYS_SKggPNwK4vaqI.woff`,
  'Cabinet Grotesk': `${FONTSHARE_CDN}/54BYDK52GK4J6SPDN2E656FIZHUETKL3/ACYE4XDNEUAHIOQEOGPYPDVAVDI5P67Q/TZVUWRP4UW5PEJWBLXHG5VVGPODI2WLC.woff`,
  'General Sans': `${FONTSHARE_CDN}/3K5C3C4RQBSGXOJBI6RNYWNNBQQKQWE2/CGHDSYGFBHIVODDSCNKU7TRVCGJ2AAMG/DHDGPCNOFIFQ5Y4BX2GXD527RTWZDCB4.woff`,
  Satoshi: `${FONTSHARE_CDN}/EGN7R737Q5WZW4FZUNCHGYUUANJFBPIC/5BJBDFKMAEMFDPL2DEHE6CEAZLV67VJF/4MQVGU6BDYFLHSZKE25U2B6SZRLWXCTQ.woff'`,
};
